### PR TITLE
Fix wording

### PR DESCRIPTION
**Pull request by bkrainer**
updates "treatments options" to "treatment options"

### CODE REVIEW

**Comment by jaykaycodes** [comment]
Not so sure about this one. Have you discussed this change with marketing? It could be the case that the "treatment's (possessive noun) options become more effective and less detrimental" , in which case an apostrophe should be added.

Also, in the future please use [proper commit messages](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by bkrainer** [comment]
@jkcorrea thanks for the feedback. Really great, wish I could just merge your feedback directly into my code it's that good haha. Don't have a marketing team , actually ,  as we are a small off-shore dev shop. I've taken your feedback into account verbatim. Mind taking another pass at this?

cc @skylarweaver

**Comment by bkrainer** [comment]
As for the previous build failure, I have narrowed it down between an issue with netlify, github, or the general architecture of the internet. As all of these things would be pretty heavy lifts, I propose merging this as-is and adding an issue to this project.

**Comment by skylarweaver** [comment]
Ah yes many thanks @bkrainer for pointing this out. While I'll close this PR b/c the text change won't work and we don't want to merge directly into Prod, I do appreciate you raising the issue regarding the "internet". Indeed it looks like we will need to refactor that. Adding it to the neverlog.

**Pull request closed without merging**
